liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"

    cache: default

    filter_sets:
        cache: ~
        pokemon:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound

        element:
            quality: 85
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
        thumbnail:
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
           
