liip_imagine:
    twig:
        mode: lazy  # Ajouter cette ligne pour résoudre la dépréciation
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"

    cache: default

    filter_sets:
        cache: ~
        thumbnail:  # Filtre générique pour tous les thumbnails
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound

        pokemon_thumb:  # Filtre spécifique pour les pokemons
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound

        element_thumb:  # Filtre spécifique pour les éléments
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
