controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_element_index:
    path: /element
    controller: App\Controller\ElementController::index


app_home:
    path: /
    controller: App\Controller\HomeController::index

app_team_show:
    path: /team
    controller: App\Controller\TeamController::index

app_youtube_search:
    path: /youtube-search
    controller: App\Controller\YoutubeController::search

app_dresseur_new:
    path: /new-dresseur
    controller: App\Controller\DresseurController::new



 

