controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_pokemon:
    path: /pokemon
    controller: App\Controller\CartController::index

app_pokemon_show:
    path: /pokemon/show
    controller: App\Controller\CartController::showCart

app_pokemon_add:
    path: /app_pokemon_add
    controller: App\Controller\CartController::addToTeam